### ISSUE TITLE
1st time activation ability is not triggered for other clients?

### ISSUE THREAD

**Issue by oivio** [GASCompanion/GASCompanionDemo#4]
Maybe it is not an issue. 

I did create the ability to self-harm and then just replaced "GA_Shoot" inside "BP_Playground_Character" with that Self-harm as on the screenshot. 
When I simply check by taking float from **_AtrributeSet.health_** Looks like 1st-time Ability Activation is not triggered for other clients.

![image](https://user-images.githubusercontent.com/38628851/178685321-079601e4-0753-4153-85fd-36b5a029e377.png)

**Comment by mklabs** [comment]
Hi @oivio thank you for the report

however, the issue is lying on how you're checking the attribute within the GA the same frame. That's not how you test / check the value of your attributes, you use the gameplay debugger for that `showdebug abilitysystem`

By the time you apply the effect, replication / prediction is going on so when you check the value on client, it hasn't been updated yet.
